export const LOGIN_REDIRECT = "LOGIN_REDIRECT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTRATION_REDIRECT = "RGISTRATION_REDIRECT";
export const REGISTRATION_SUCCESS = "RGISTRATION_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";